name: Validate Dependabot
on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Dependabot Config
        uses: pipelinedigital/validate-dependabot-config@v1
